<?php
  /**************************************************************************\
  * eGroupWare - Setup                                                       *
  * http://www.egroupware.org                                                *
  * --------------------------------------------                             *
  *  This program is free software; you can redistribute it and/or modify it *
  *  under the terms of the GNU General Public License as published by the   *
  *  Free Software Foundation; either version 2 of the License, or (at your  *
  *  option) any later version.                                              *
  \**************************************************************************/

  /* $Id: default_records.inc.php,v 1.6.2.1 2004/07/25 01:34:56 ralfbecker Exp $ */

  /* Commented entries are no longer available, as of Oct 22, 2003 - shrykedude */

	$data_columns = '(data_enabled,data_name,data_author,data_title,data_prefix,data_date,data_comicid,data_linkurl,data_baseurl,data_parseurl,data_parsexpr,data_imageurl,data_pubdays,data_parser,data_class,data_censorlvl,data_resolve,data_daysold,data_width,data_swidth)';

	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','userfriendly','Illiad','User Friendly','',0,0,'http://www.userfriendly.org/static/','http://www.userfriendly.org','/cartoons/archives/{y}{Ml}/{Ymd}.html','/cartoons/archives/{y}{Ml}/uf[0-9]*.gif','','Su:Mo:Tu:We:Th:Fr:Sa','None','Geek',1,'Remote',0,720,720)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','dilbert','Scott Adams','Dilbert','',0,0,'http://www.dilbert.com/','http://www.comics.com','/comics/dilbert/index.html','/comics/dilbert/archive/images/dilbert[0-9]*.gif','','Su:Mo:Tu:We:Th:Fr:Sa','None','Geek',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','garfield','Jim Davis','Garfield','ga',0,0,'http://www.garfield.com/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','foxtrot','Bill Amend','FoxTrot','ft',0,0,'http://www.foxtrot.com/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','babyblue','Jerry Scott & Rick Kirkman','Baby Blues','',0,0,'http://www.babyblues.com/','http://est.rbma.com/content/Baby_Blues?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Static',14,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','tumblewd','Tom K. Ryan','Tumbleweeds','',0,0,'http://www.tumbleweeds.com/','http://www.tumbleweeds.com/images/{day}.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Static',0,525,525)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','jerkcity','TBD','JerkCity','',0,0,'http://www.jerkcity.com/','http://www.jerkcity.com/today.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','Geek',2,'Static',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','slagoon','Jim Toomey','Shermans Lagoon','',0,0,'http://www.slagoon.com/','http://www.slagoon.com/dailies/SL{y}.{m}.{d}.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Static',0,576,650)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','blondie','Dean Young and Denis Lebrun','Blondie','',0,0,'http://www.blondie.com/','http://www.blondie.com/dailies/blondie.{Ymd}.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Static',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','sluggy','Pete Abrams','Sluggy Freelance','',0,0,'http://www.sluggy.com/','http://pics.sluggy.com/comics/{ymd}a.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','Geek',0,'Static',0,700,700)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','ripleys','Don Wimmer and Karen Kemlo','Ripleys Believe It Or Not','',0,0,'','','','','','Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,300,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','buckets','Scott Stantis','Buckets','',0,0,'http://www.unitedmedia.com/comics/buckets/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','fatcats','Charlie Podrebarac','Fat Cats','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','getfuzzy','Darby Conley','Get Fuzzy','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','topofworld','Mark Tonra','Top Of This World','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','meatloaf','Mark Buford','Meatloaf Night','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','tarzan','Gray Morrow','Tarzan','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','spidermn','Stan Lee','The Amazing Spider-Man','Spiderman',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','apt3g','Brian Kotzky & Lisa Trusiani','Apartment 3-G','Apartment_3-G',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bgoogle','Fred Lasswell','Barney Google and Snuffy Smith','Barney_Google',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bbailey','Mort Walker','Beetle Bailey','Beetle_Bailey',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bet_half','Randy Glasbergen','The Better Half','Better_Half',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,249,249)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bfriends','Sandra Bell-Lundy','Between Friends','Between_Friends',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bonerark','Frank Johnson','Boners Ark','bot',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','bfather','Frank Johnson','Bringing Up Father','brt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','buckles','David Gilbert','Buckles','Buckles',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','claire','Doug Shannon','Claire and Weber','cwt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','crock','Bill Rechin & Don Wilder','Crock','Crock',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','curtis','Ray Billingsley','Curtis','curt',0,104,'http://www.kingfeatures.com/features/comics/curtis/aboutMaina.php','http://est.rbma.com/content/Curtis?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Remote',14,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','dennis','Hank Ketcham','Dennis The Menace','Dennis_The_Menace',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,251,251)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','dinette','Julie Larson','Dinette Set','Dinette_Set',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,251,251)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','familycircus','Bil Keane','The Family Circus','fam',0,109,'http://www.kingfeatures.com/features/comics/familyc/about.htm','http://est.rbma.com/content/Family_Circus?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Remote',14,263,263)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','fgordon','Jim Keefe','Flash Gordon','fg',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','Funky','Tom Batiuk','Funky Winkerbean','funk',0,124,'http://www.kingfeatures.com/features/comics/fwinker/about.htm','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Toonville','General',0,'Remote',0,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','grinbear','Fred Wagner & Ralph Dunagin','Grin and Bear It','Grin_and_Bear_It',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,250,250)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','hagar','Chris Browne','Hagar the Horrible','Hagar_The_Horrible',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','hazel','Ted Key','Hazel','hat',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,243,243)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','henry','TBD','Henry','het',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','horrscpe','Susan Kelso & Carol Kemp','Horrorscope','hrt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,240,240)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','needhelp','Vic Lee','I Need Help','I_Need_Help',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,263,263)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','jparker','Woody Wilson & Harold LeDoux','Judge Parker','Judge_Parker',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','katzkids','Hy Eisman','Katzenjammer Kids','kk',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','lockhorn','Bunny Hoest & John Reiner','The Lockhorns','Lockhorns',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,249,249)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','mallard','Bruce Tinsley','Mallard Fillmore','Mallard_Fillmore',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','Political',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','mandrake','Lee Falk & Fred Fredericks','Mandrake the Magician','mmt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','mtrail','Jack Elrod','Mark Trail','Mark_Trail',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','marvin','Tom Armstrong','Marvin','Marvin',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','mmiller','Bob Weber Sr','Moose Miller','mot',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','mutts','Patrick McDonnell','Mutts','Mutts',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','fastrack','Bill Holbrook','On The Fastrack','Fast_Track',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','ernie','Bud Grace','The Piranha Club','Piranha',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','popeye','TBD','Popeye','Popeye',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','popplace','Sam C Rawls','Pops Place','ppt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','pvaliant','John Cullen Murphy & Cullen Murphy','Prince Valiant','val',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,750,750)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','ralph','Wayne Stayskal','Ralph','Ralph',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,248,248)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','redeye','Bill Yates & Mel Casson','Red Eye','Redeye',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','orange','Hilary Price','Rhymes With Orange','Rhymes_with_Orange',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','safehavn','Bill Holbrook','Safe Havens','Safe_Havens',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','sforth','Greg Howard & Craig MacIntosh','Sally Forth','Sally_Forth',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,525,525)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','sam_silo','Jerry Dumas','Sam and Silo','sst',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','sixchix','Isabella Bannerman, Margaret Shuloc k, Rina Piccolo, Ann C. Telnaes, Kathryn LeMieux, and Stephanie Piro','Six Chix','6Chix',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','sroper','John Saunders & Fran Matera','Steve Roper & Mike Nomad','Steve_Roper',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','theydoit','Al Scaduto','They Do It Every Time','TDIE',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,246,246)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','tiger','Bud Blake','Tiger','Tiger',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','trudy','Jerry Marcus','Trudy','trt',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,247,247)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','willy','Joe Martin','Willy and Ethel','Willy_n_Ethel',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('F','zippy','Bill Griffith','Zippy','Zippy_the_Pinhead',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','Zits','Jerry Scott & Jim Borgman','Zits','zits',0,145,'','http://est.rbma.com/content/Zits?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','fredbasset','Alex Graham','Fred Basset','tmfba',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',7,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','boundandgagged','Dana Summers','Bound & Gagged','tmbou',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','middletons','Ralph Dunagin & Dana Summers','The Middletons','tmmid',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','pluggers','Brookins (Submissions)','Pluggers','tmplu',0,0,'http://www.ucomics.com/pluggers/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','ComicsPage','General',0,'Remote',0,300,580)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','alleyoop','Dave Gaue & Jack Bender','Alley Oop','',0,0,'http://www.comics.com/comics/alleyoop/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','arlonjanis','Jimmy Johnson','Arlo and Janis','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','betty','Gary Delainey & Gerry Rasmussen','Betty','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','bornloser','Chip Sansom','The Born Loser','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','committed','Michael Fry','Committed','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,300,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','drabble','Kevin Fagan','Drabble','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','forbetter','Lynn Johnston','For Better or For Worse','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','grizzwells','Bill Schorr','The Grizzwells','',0,0,'','','','','','Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,0)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','herman','Jim Unger','Herman','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,300,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','jumpstart','Robb Armstrong','JumpStart','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','kitncarlyle','Larry Wright','Kit-n-Carlyle','',0,0,'','','','','','Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,300,0)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','liberty','Frank Cho','Liberty Meadows','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Creators','General',0,'Remote',0,625,650)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','luann','Greg Evans','Luann','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','marmaduke','Brad Anderson','Marmaduke','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,300,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','meg','Greg Curfman','Meg!','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','nancy','Guy and Brad Gilchrist','Nancy','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','hedge','Michael Fry and T. Lewis','Over The Hedge','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','peanuts','Charles Schulz','Peanuts','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','robotman','Jim Meddick','Robotman','monty',0,0,'http://www.unitedmedia.com/comics/robotman/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','roseisrose','Pat Brady','Rose is Rose','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,725)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','adam','Brian Basset','Adam at Home','ad',0,0,'http://www.ucomics.com/adamathome/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','boondocks','Aaron McGruder','The Boondocks','bo',0,0,'http://www.ucomics.com/boondocks/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','cathy','Cathy Guisewite','Cathy','ca',0,0,'http://www.ucomics.com/cathy/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','citizendog','".$oProc->m_odb->db_addslashes('Mark O\'Hare')."','Citizen Dog','cd',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','closehome','John McPherson','Close to Home','cl',0,0,'http://www.ucomics.com/closetohome/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,300,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','cornered','Mike Baldwin','Cornered','co',0,0,'http://www.ucomics.com/cornered/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,300,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','crankshaft','Tom Batiuk & Chuck Ayers','Crankshaft','cs',0,0,'http://www.ucomics.com/crankshaft/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',14,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','duplex','Glenn McCoy','The Duplex','dp',0,0,'http://www.ucomics.com/duplex/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','fifthwave','Rich Tennant','Fifth Wave','fw',0,0,'http://www.ucomics.com/thefifthwave/','','','','','Su','Ucomics','General',0,'Remote',0,0,500)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','geech','Jerry Bittle','Geech','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','heartcity','Mark Tatulli','Heart of the City','hc',0,0,'http://www.ucomics.com/heartofthecity/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','bleachers','Steve Moore','In the Bleachers','bl',0,0,'http://www.ucomics.com/inthebleachers/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,300,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','mrboffo','Joe Martin','Mister Boffo','mb',0,0,'http://www.ucomics.com/misterboffo/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','overboard','Chip Dunham','Overboard','ob',0,0,'http://www.ucomics.com/overboard/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','hth','George Gately','Heathcliff','hth',0,101,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Creators','General',0,'Remote',0,300,300)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','stonesoup','Jan Eliot','Stone Soup','ss',0,0,'http://www.ucomics.com/stonesoup/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','reallife','Gary Wise & Lance Aldrich','Real Life Adventures','rl',0,0,'http://www.ucomics.com/reallifeadventures/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,300,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','tmcnamara','Jeff Millar & Bill Hinds','Tank McNamara','tm',0,0,'http://www.ucomics.com/tankmcnamara/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','baldo','Geof Brooks','Baldo','ba',0,0,'http://www.ucomics.com/baldo/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','ziggy','Tom Wilson','Ziggy','',0,0,'','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Comiczone7','General',0,'Remote',0,300,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','fuscobros','Joe Duffy','The Fusco Brothers','fu',0,0,'http://www.ucomics.com/thefuscobrothers/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','doonesbury','G. B. Trudeau','Doonesbury','db',0,0,'http://www.doonesbury.com/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','Political',0,'Remote',0,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','shoe','Jeff McNelly','Shoe','',0,0,'http://macnelly.com/shoe_page.html','http://macnelly.com/shoe_images{m}{y}/shoe_daily{m}{d}{y}.jpg','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Static',0,612,1047)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','calvinandhobbes','Bill Watterson','Calvin and Hobbes','ch',0,0,'http://www.calvinandhobbes.com/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','Ucomics','General',0,'Remote',4018,600,600)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','boll','Ruben Bolling','Tom The Dancing Bug','td',0,0,'http://www.ucomics.com/tomthedancingbug/','','','','','Sa','Ucomics','General',0,'Remote',0,480,480)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','frankernest','Bob Thaves','Frank and Ernest','frank',0,126,'http://www.unitedmedia.com/comics/franknernest/','','','','','Su:Mo:Tu:We:Th:Fr:Sa','United','General',0,'Remote',0,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','KevKel','Bill Holbrook','Kevin & Kell','kk',0,149,'http://www.kevinandkell.com/','http://www.kevinandkell.com/{y}/strips/kk{y}{m}{d}.gif','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Remote',0,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','Hilois','Browne, Walker, and Walker','Hi and Lois','Hi',0,105,'http://www.kingfeatures.com/features/comics/hi_lois/about.htm','http://est.rbma.com/content/Hi_and_Lois?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','None','General',0,'Remote',0,585,585)");
	$oProc->query("INSERT INTO phpgw_comic_data $data_columns VALUES ('T','Grimmy','Mike Peters','Mother Goose & Grimm','tmmgg',0,148,'http://www.kingfeatures.com/features/comics/grimmy/about.htm','http://est.rbma.com/content/Mgoose?date={y}{m}{d}','','','','Su:Mo:Tu:We:Th:Fr:Sa','King','General',0,'Remote',0,600,600)");
?>
