ALTER TABLE `phpgw_categories` ADD `order` INT( 11 ) DEFAULT '0' NOT NULL ;
INSERT INTO `phpgw_categories` VALUES (75, 75, 0, 0, 7, 'public', 'vanilla', 'Business Ideas for Milan IN', 'Le idee di Business per Milan IN', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (54, 54, 0, 0, 7, 'public', 'vanilla', 'General Business Ideas', '', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (55, 55, 0, 0, 7, 'public', 'vanilla', 'Official Club Meetings (Social Networking Events)', 'The meetings, organized by the Org-Committee', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (56, 56, 0, 0, 7, 'public', 'vanilla', 'Job Offers', 'Offerte di lavoro pervenute a Milan IN', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (57, 57, 0, 0, 7, 'public', 'vanilla', 'Guest Book', 'Give us your opinions about the Club!', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (58, 58, 0, 0, 7, 'public', 'vanilla', 'General Topic', 'Any other issues except Offtopic/Junk', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (59, 59, 0, 0, 7, 'public', 'vanilla', 'Business Opportunity', 'Business Offers, Looking for Partners, etc.\r\n(Inserite qui le vostre idee di Business)', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (60, 60, 0, 0, 8, 'public', 'vanilla', 'Milan IN Web-Site and "eGroupWare" Collaboration Tool', 'Any critics, ideas for enhancements, comments, etc.', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (61, 61, 0, 0, 7, 'public', 'vanilla', 'Club Members'' Self- Presentation', 'Let''s explain here who we are and what is our interest in Business and B.C.', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (62, 62, 0, 0, 7, 'public', 'vanilla', 'Milan IN FAQ', 'What every Club Member must know about the B.C. Milan-IN', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (63, 63, 0, 0, 7, 'public', 'vanilla', 'Social Networking and Linked-In', 'Let''s discuss here the things around Social Networking and particularly Linked-In', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (64, 64, 0, 0, 7, 'public', 'vanilla', 'Test Forum', 'Do here whatever you need to check the forum.', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (65, 65, 0, 0, 7, 'public', 'vanilla', 'Closed Group Discussions', 'For co-founders only', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (66, 66, 0, 0, 7, 'public', 'vanilla', 'Ad-hoc Meetings', 'Organizziamo un nuovo meeting?', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (67, 67, 0, 0, 17, 'public', 'vanilla', 'IT/Web Support', 'Limited to IT/Web group', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (68, 68, 0, 0, 7, 'public', 'vanilla', 'Marketing and Promotion', 'Limited to Marketing Group', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (69, 69, 0, 0, 7, 'public', 'vanilla', 'Finance and Controlling', 'Limited to Finance & Controlling Group', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (70, 70, 0, 0, 7, 'public', 'vanilla', 'Project Management and Operations', 'Limited to Operative Management', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (71, 71, 0, 0, 7, 'public', 'vanilla', 'Internationalization and External Affairs', 'Limited to External Affairs Group', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (72, 72, 0, 0, 8, 'public', 'vanilla', 'Offtopic', 'Hot News, emotions, weather, etc. ;)', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (73, 73, 0, 0, 8, 'public', 'vanilla', 'Looking for a Job', 'Cerco lavoro (come dipendente)', '', 0, 0);
INSERT INTO `phpgw_categories` VALUES (74, 74, 0, 0, 8, 'public', 'vanilla', 'Internet/ Computers/ Software/ etc.', 'Internet/ Computers/ Software/ etc.', '', 0, 0);
