delete FROM `template_elements` WHERE `template_id`=6;
INSERT INTO `template_elements` VALUES (25229, 'msg1:title1:language3', 'ru msg1:message body1 text russian', 6);
INSERT INTO `template_elements` VALUES (25228, 'msg2:title2:language2', 'it msg2:message body2 text italiano', 6);
INSERT INTO `template_elements` VALUES (25227, 'msg1:title1:language2', 'ti scrivo per farti conoscere il più attivo e numeroso Club degli utenti LinkedIn di Milano: il Business Club Milan IN (www.milanin.com).\\n\\nSiamo più di <<$members_count>> soci (imprenditori, giovani quadri e dirigenti, professionisti etc..), organizziamo incontri di business social networking e saremmo lieti di averti tra i nostri iscritti.\\n\\nE'' un modo per espandere il proprio network di conoscenze professionali.\\n\\nSul sito www.milanin.com puoi trovare tutti i dettagli, il modulo per l''iscrizione, lo statuto e i nomi dei fondatori dell''associazione.\\n\\nGrazie per l''attenzione,\\n\\nCordiali saluti,', 6);
INSERT INTO `template_elements` VALUES (25226, 'msg3:title3:language1', 'en msg3:message body3 text english', 6);
INSERT INTO `template_elements` VALUES (25225, 'msg2:title2:language1', 'en msg2:message body2 text english', 6);
INSERT INTO `template_elements` VALUES (25224, 'msg1:title1:language1', 'i''m inviting you to Milanin that is LinkedIn users club in Milano: il Business Club Milan IN (www.milanin.com).\\n\\nWe are  <<$members_count>> members............,', 6);
INSERT INTO `template_elements` VALUES (25223, 'title1:language3', 'ru title1:Title1 text', 6);
INSERT INTO `template_elements` VALUES (25222, 'title2:language2', 'it title2:Title2 text', 6);
INSERT INTO `template_elements` VALUES (25220, 'title3:language1', 'en title3:Title3 text', 6);
INSERT INTO `template_elements` VALUES (25221, 'title1:language2', 'it title1:Title1 text', 6);
INSERT INTO `template_elements` VALUES (25219, 'title2:language1', 'en title2:Title2 text', 6);
INSERT INTO `template_elements` VALUES (25218, 'title1:language1', 'Invito al club', 6);
INSERT INTO `template_elements` VALUES (25216, 'language2', 'Italian', 6);
INSERT INTO `template_elements` VALUES (25217, 'language3', 'Russian', 6);
INSERT INTO `template_elements` VALUES (25215, 'language1', 'English', 6);
INSERT INTO `template_elements` VALUES (25230, 'salut1:language1', 'Dear', 6);
INSERT INTO `template_elements` VALUES (25231, 'salut2:language1', 'Hi', 6);
INSERT INTO `template_elements` VALUES (25232, 'salut1:language2', 'Gentile', 6);
INSERT INTO `template_elements` VALUES (25233, 'salut2:language2', 'Hi', 6);
